# Generated by Django 4.0.6 on 2022-08-24 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='채용포지션')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(verbose_name='채용보상금')),
                ('area', models.CharField(max_length=128, verbose_name='지역')),
                ('country', models.CharField(max_length=128, verbose_name='국가')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company', verbose_name='회사')),
                ('jopposition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobpost.jobposition', verbose_name='채용포지션')),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='사용기술')),
            ],
        ),
        migrations.CreateModel(
            name='JobPostSkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobpost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobpost.jobpost')),
                ('skillset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobpost.skillset')),
            ],
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skillset',
            field=models.ManyToManyField(through='jobpost.JobPostSkillSet', to='jobpost.skillset', verbose_name='사용기술'),
        ),
    ]
