# Generated by Django 4.0.6 on 2022-08-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0002_rename_jopposition_jobpost_jobposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='content',
            field=models.TextField(null=True, verbose_name='채용내용'),
        ),
    ]
