# Generated by Django 4.0.6 on 2022-08-24 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobpost', '0004_alter_jobpost_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='지원 시간')),
                ('jobpost', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobpost.jobpost', verbose_name='채용공고')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='지원자')),
            ],
        ),
    ]
